# Status bar colours
set -g status-bg colour235
set -g status-fg white
set-window-option -g window-status-current-style bg=colour25,fg=colour232
set -g status-justify centre

# Escape isn't delayed anymore
set -s escape-time 0

# Vi mode
setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
